host = "0.0.0.0"
port = 3335
# Host and Port for the Receiver

output = "ui/print/discord"
# ui      = cool interactive ui
# print   = simple log
# discord = discord webhooks

webhook = ""
# your webhook url in case you set "discord" for output